# Generated by Django 3.2.8 on 2021-11-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_userinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='myskills/media/uploads'),
        ),
    ]
